#!/usr/bin/env bash
# Display "Best School" 10 times
i=1
while [ "$1" -le 10 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elsif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
